// src/constants/ajudaSearchIndex.ts

export interface HelpSearchEntry {
  id: string;
  areaId: string;
  title: string;
  href: string;
  summary: string;
  keywords?: string[];
}

export const ajudaSearchIndex: HelpSearchEntry[] = [
  {
    id: "primeiros-passos-o-que-e",
    areaId: "primeiros-passos",
    title: "O que é o VigiaSUS?",
    href: "/ajuda/primeiros-passos/o-que-e",
    summary: "Visão geral da plataforma VigiaSUS, seus objetivos e como os contextos se organizam na central.",
    keywords: ["introducao", "plataforma", "conceitos", "primeiros passos", "contextos"],
  },
  {
    id: "primeiros-passos-navbar",
    areaId: "primeiros-passos",
    title: "Barra de Navegação",
    href: "/ajuda/primeiros-passos/navbar",
    summary: "Mapa completo da navbar: menu lateral, status do sistema, notificações e atalhos principais.",
    keywords: ["navbar", "menu", "notificacoes", "sino", "atalhos"],
  },
  {
    id: "primeiros-passos-sidebar",
    areaId: "primeiros-passos",
    title: "Menu Lateral",
    href: "/ajuda/primeiros-passos/sidebar",
    summary: "Como o menu lateral organiza as páginas do VigiaSUS de acordo com o perfil do usuário.",
    keywords: ["sidebar", "menu lateral", "navegacao", "links", "perfil"],
  },
  {
    id: "primeiros-passos-perfis",
    areaId: "primeiros-passos",
    title: "Perfis de Usuário",
    href: "/ajuda/primeiros-passos/perfis",
    summary: "Diferenças entre os perfis Membro, Gerente, Diretor e Secretário e suas permissões.",
    keywords: ["perfis", "permissoes", "membro", "gerente", "diretor", "secretario"],
  },
  {
    id: "gerenciando-conteudo-o-que-e-contexto",
    areaId: "gerenciando-conteudo",
    title: "O que é um Contexto?",
    href: "/ajuda/gerenciando-conteudo/o-que-e-contexto",
    summary: "Entenda os tipos de contexto (arquivos, links, dashboards e indicadores) e quando usar cada um.",
    keywords: ["contexto", "arquivo", "link", "dashboard", "indicador"],
  },
  {
    id: "gerenciando-conteudo-add-arquivo-link",
    areaId: "gerenciando-conteudo",
    title: "Guia: Adicionando Arquivos ou Links",
    href: "/ajuda/gerenciando-conteudo/add-arquivo-link",
    summary: "Passo a passo para anexar documentos, inserir URLs e enviar o contexto para validação.",
    keywords: ["upload", "arquivo", "link", "anexo", "submeter"],
  },
  {
    id: "gerenciando-conteudo-add-grafico",
    areaId: "gerenciando-conteudo",
    title: "Guia: Criando Gráficos",
    href: "/ajuda/gerenciando-conteudo/add-grafico",
    summary: "Como construir dashboards com dados manuais ou CSV, escolher tipos de gráfico e pré-visualizar.",
    keywords: ["dashboard", "grafico", "csv", "pizza", "barras", "pre-visualizacao"],
  },
  {
    id: "gerenciando-conteudo-add-indicador",
    areaId: "gerenciando-conteudo",
    title: "Guia: Adicionando Indicadores",
    href: "/ajuda/gerenciando-conteudo/add-indicador",
    summary: "Configure KPIs com valor atual, meta, unidade, texto comparativo, cor e ícone.",
    keywords: ["indicador", "kpi", "meta", "valor atual", "texto comparativo"],
  },
  {
    id: "gerenciando-conteudo-nova-versao",
    areaId: "gerenciando-conteudo",
    title: "Como criar uma Nova Versão",
    href: "/ajuda/gerenciando-conteudo/nova-versao",
    summary: "Quando um contexto precisa de atualização, aprenda a abrir uma nova versão com histórico controlado.",
    keywords: ["nova versao", "historico", "atualizacao", "correcao"],
  },
  {
    id: "visualizando-dados-dados-gerais",
    areaId: "visualizando-dados",
    title: "O que são Dados Gerais?",
    href: "/ajuda/visualizando-dados/dados-gerais",
    summary: "Conheça a página de Dados Gerais, filtros de gerências e como navegar pelo panorama da secretaria.",
    keywords: ["dados gerais", "diretorias", "gerencias", "carrossel", "filtros"],
  },
  {
    id: "visualizando-dados-pagina-gerencia",
    areaId: "visualizando-dados",
    title: "A Página da Gerência",
    href: "/ajuda/visualizando-dados/pagina-gerencia",
    summary: "Estrutura da página de uma gerência: dashboards, indicadores, filtros e seção Sobre.",
    keywords: ["pagina da gerencia", "indicadores", "cards", "contextos", "modo de edicao"],
  },
  {
    id: "visualizando-dados-dashboard",
    areaId: "visualizando-dados",
    title: "O Dashboard (Diretor/Secretaria)",
    href: "/ajuda/visualizando-dados/dashboard",
    summary: "Diferenças entre o dashboard do secretário e o painel do diretor, layouts e destaques.",
    keywords: ["dashboard", "diretor", "secretaria", "layout", "destaques"],
  },
  {
    id: "visualizando-dados-modal-visualizacao",
    areaId: "visualizando-dados",
    title: "Visualizando Detalhes (Modal)",
    href: "/ajuda/visualizando-dados/modal-visualizacao",
    summary: "Como usar o modal de detalhes para baixar arquivos, abrir links, ver histórico e comentários.",
    keywords: ["modal", "detalhes", "download", "historico", "comentarios"],
  },
  {
    id: "validacao-fluxo",
    areaId: "validacao",
    title: "Fluxo de Validação",
    href: "/ajuda/validacao/fluxo",
    summary: "Entenda as etapas de aprovação: Membro, Gerente, Diretor e publicação final.",
    keywords: ["validacao", "fluxo", "deferir", "publicado", "aguardando"],
  },
  {
    id: "validacao-acoes",
    areaId: "validacao",
    title: "Ações: Deferir/Indeferir",
    href: "/ajuda/validacao/acoes",
    summary: "O que acontece ao aprovar ou pedir correção, justificativas e retorno ao membro.",
    keywords: ["deferir", "indeferir", "correcao", "justificativa", "acoes"],
  },
  {
    id: "validacao-notificacoes",
    areaId: "validacao",
    title: "Central de Notificações",
    href: "/ajuda/validacao/notificacoes",
    summary: "Tipos de alertas enviados pela central: validações pendentes, status e avisos do sistema.",
    keywords: ["notificacoes", "alertas", "sino", "pendencias", "avisos"],
  },
  {
    id: "validacao-comentarios",
    areaId: "validacao",
    title: "Comentários e Histórico",
    href: "/ajuda/validacao/comentarios",
    summary: "Acompanhe discussões, justificativas e trilha de auditoria dentro do contexto.",
    keywords: ["comentarios", "historico", "auditoria", "linha do tempo"],
  },
  {
    id: "modulos-cms",
    areaId: "modulos",
    title: "Guia: Conselho Municipal de Saúde (CMS)",
    href: "/ajuda/modulos/cms",
    summary: "Publicação de eventos, resoluções e leis dentro do módulo do Conselho Municipal de Saúde.",
    keywords: ["cms", "modulos", "eventos", "resolucoes", "leis"],
  },
  {
    id: "suporte-contato",
    areaId: "suporte",
    title: "Contato com a GTI",
    href: "/ajuda/suporte/contato",
    summary: "Canais oficiais para abrir chamados, telefone e horários de atendimento da equipe de TI.",
    keywords: ["suporte", "contato", "gti", "chamado", "email"],
  },
  {
    id: "suporte-reportar-bug",
    areaId: "suporte",
    title: "Reportar um Problema",
    href: "/ajuda/suporte/reportar-bug",
    summary: "Checklist de informações para relatar bugs, capturas de tela e como priorizamos a correção.",
    keywords: ["bug", "problema", "erro", "relato", "prioridade"],
  },
  {
    id: "suporte-faq",
    areaId: "suporte",
    title: "Perguntas Frequentes (FAQ)",
    href: "/ajuda/suporte/faq",
    summary: "Respostas rápidas sobre acesso, permissões, notificações e atualização de dados.",
    keywords: ["faq", "perguntas frequentes", "duvidas", "permissoes", "acesso"],
  },
];
